{
  imports = [
    ./apps.nix
    ./profiles.nix
    ./readiness
    ./integration
    ./integrations/jellyfin.nix
    ./integrations/prowlarr.nix
    ./integrations/seerr.nix
    ./integrations/servarr.nix
    ./operations
    ./optional
    ./storage
    ./arrs
    ./downloaders/nzbget.nix
    ./downloaders/sabnzbd.nix
    ./downloaders/qbittorrent.nix
    ./indexers/prowlarr.nix
    ./indexers/proxy.nix
    ./media
    ./request/seerr.nix
    ./services/audiomuse-ai.nix
    ./vpn/wireguard.nix
  ];
}
